on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Once a day at 01:12.
    - cron:  '12 1 * * *'
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2

      - name: Cache build directory
        uses: actions/cache@v3
        with:
          path: build/
          key: ${{ runner.os }}-build-
          restore-keys: ${{ runner.os }}-build-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --optimize-autoloader --no-progress

      - name: Build 9.x
        run: |
          mkdir build/ -p
          time php console.php build:composer
          ls -la build/
